name: Detekt
on:
  pull_request:
    branches: [ main ]
jobs:
  detekt:
    name: Detekt
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone repo
        uses: actions/checkout@v2
      - name: detekt
        uses: alaegin/Detekt-Action@v1.18.1.2
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: detekt-config.yml
          reviewdog_level: warning
          reviewdog_reporter: github-pr-review
          fail_on_error: true
          detekt_baseline: app/detekt-baseline.yml