name: Lint
on:
  pull_request:
    branches: [ main ]
jobs:
  ktlint:
    name: KtLint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          level: warning
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter
